"""initial schema

Revision ID: 5d6810f1b31f
Revises: 
Create Date: 2026-08-04 11:57:50.025707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d6810f1b31f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('detail_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entity_type IN ('sprint', 'task', 'note', 'kb', 'time', 'inbox', 'attachment')", name='ck_activity_entity_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_created', 'activity_log', ['created_at'], unique=False)
    op.create_index('idx_activity_entity', 'activity_log', ['entity_type', 'entity_id'], unique=False)
    op.create_table('inbox_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('resolved_to', sa.Text(), nullable=True),
    sa.Column('resolved_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("resolved_to IN ('task', 'note', 'kb', 'dismissed')", name='ck_inbox_resolved_to'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inbox_resolved', 'inbox_items', ['resolved_to'], unique=False)
    op.create_table('sprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('goals_summary', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Text(), server_default='planned', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('planned', 'active', 'closed')", name='ck_sprints_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), server_default='#6B7280', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('template_type', sa.Text(), nullable=False),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("template_type IN ('task', 'meeting_note', 'sprint')", name='ck_templates_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurring_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description_md', sa.Text(), nullable=True),
    sa.Column('frequency', sa.Text(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('tag_names', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_created_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("frequency IN ('daily', 'weekly', 'monthly')", name='ck_recurring_frequency'),
    sa.CheckConstraint('day_of_month BETWEEN 1 AND 31', name='ck_recurring_dom'),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name='ck_recurring_dow'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sprint_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sprint_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('progress_pct', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('progress_pct BETWEEN 0 AND 100', name='ck_sprint_goals_progress'),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sprint_retros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sprint_id', sa.Integer(), nullable=False),
    sa.Column('went_well', sa.Text(), nullable=True),
    sa.Column('needs_improvement', sa.Text(), nullable=True),
    sa.Column('action_items', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sprint_id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sprint_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description_md', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='todo', nullable=False),
    sa.Column('priority', sa.Text(), server_default='medium', nullable=False),
    sa.Column('task_type', sa.Text(), server_default='general', nullable=False),
    sa.Column('ticket_id', sa.Text(), nullable=True),
    sa.Column('ticket_url', sa.Text(), nullable=True),
    sa.Column('estimated_hours', sa.Numeric(), nullable=True),
    sa.Column('actual_hours', sa.Numeric(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('carried_from_task_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high', 'urgent')", name='ck_tasks_priority'),
    sa.CheckConstraint("status IN ('todo', 'in_progress', 'review', 'done')", name='ck_tasks_status'),
    sa.CheckConstraint("task_type IN ('general', 'development')", name='ck_tasks_type'),
    sa.ForeignKeyConstraint(['carried_from_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_carried', 'tasks', ['carried_from_task_id'], unique=False)
    op.create_index('idx_tasks_due_date', 'tasks', ['due_date'], unique=False)
    op.create_index('idx_tasks_sprint', 'tasks', ['sprint_id'], unique=False)
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=True),
    sa.Column('note_type', sa.Text(), server_default='general', nullable=False),
    sa.Column('attendees', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), server_default='manual', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(title,'') || ' ' || coalesce(content_md,''))", persisted=True), nullable=True),
    sa.CheckConstraint("note_type IN ('general', 'meeting', 'standup', 'retro')", name='ck_notes_type'),
    sa.CheckConstraint("source IN ('manual', 'claude_code', 'claude_desktop')", name='ck_notes_source'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notes_search_vector', 'notes', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_notes_source', 'notes', ['source'], unique=False)
    op.create_index('idx_notes_task', 'notes', ['task_id'], unique=False)
    op.create_index('idx_notes_type', 'notes', ['note_type'], unique=False)
    op.create_table('task_tags',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'tag_id')
    )
    op.create_table('time_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('log_type', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_hours', sa.Numeric(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("log_type IN ('punch_in', 'punch_out', 'task_time')", name='ck_time_logs_type'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_time_logs_start', 'time_logs', ['start_time'], unique=False)
    op.create_index('idx_time_logs_task', 'time_logs', ['task_id'], unique=False)
    op.create_index('idx_time_logs_type', 'time_logs', ['log_type'], unique=False)
    op.create_table('kb_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('source_note_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(title,'') || ' ' || coalesce(content_md,''))", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['source_note_id'], ['notes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kb_category', 'kb_articles', ['category'], unique=False)
    op.create_index('idx_kb_search_vector', 'kb_articles', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('note_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_note_id', sa.Integer(), nullable=False),
    sa.Column('to_note_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.Text(), server_default='reference', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("link_type IN ('reference', 'related', 'followup')", name='ck_note_links_type'),
    sa.ForeignKeyConstraint(['from_note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_note_id', 'to_note_id', name='uq_note_links_from_to')
    )
    op.create_index('idx_note_links_from', 'note_links', ['from_note_id'], unique=False)
    op.create_index('idx_note_links_to', 'note_links', ['to_note_id'], unique=False)
    op.create_table('note_tags',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id', 'tag_id')
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('kb_article_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_type', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('source', sa.Text(), server_default='upload', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('upload', 'claude_code', 'clipboard')", name='ck_attachments_source'),
    sa.CheckConstraint('(task_id IS NOT NULL AND note_id IS NULL AND kb_article_id IS NULL) OR (task_id IS NULL AND note_id IS NOT NULL AND kb_article_id IS NULL) OR (task_id IS NULL AND note_id IS NULL AND kb_article_id IS NOT NULL)', name='ck_attachments_one_parent'),
    sa.ForeignKeyConstraint(['kb_article_id'], ['kb_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attachments_kb', 'attachments', ['kb_article_id'], unique=False)
    op.create_index('idx_attachments_note', 'attachments', ['note_id'], unique=False)
    op.create_index('idx_attachments_task', 'attachments', ['task_id'], unique=False)
    op.create_table('kb_tags',
    sa.Column('kb_article_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kb_article_id'], ['kb_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('kb_article_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kb_tags')
    op.drop_index('idx_attachments_task', table_name='attachments')
    op.drop_index('idx_attachments_note', table_name='attachments')
    op.drop_index('idx_attachments_kb', table_name='attachments')
    op.drop_table('attachments')
    op.drop_table('note_tags')
    op.drop_index('idx_note_links_to', table_name='note_links')
    op.drop_index('idx_note_links_from', table_name='note_links')
    op.drop_table('note_links')
    op.drop_index('idx_kb_search_vector', table_name='kb_articles', postgresql_using='gin')
    op.drop_index('idx_kb_category', table_name='kb_articles')
    op.drop_table('kb_articles')
    op.drop_index('idx_time_logs_type', table_name='time_logs')
    op.drop_index('idx_time_logs_task', table_name='time_logs')
    op.drop_index('idx_time_logs_start', table_name='time_logs')
    op.drop_table('time_logs')
    op.drop_table('task_tags')
    op.drop_index('idx_notes_type', table_name='notes')
    op.drop_index('idx_notes_task', table_name='notes')
    op.drop_index('idx_notes_source', table_name='notes')
    op.drop_index('idx_notes_search_vector', table_name='notes', postgresql_using='gin')
    op.drop_table('notes')
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_sprint', table_name='tasks')
    op.drop_index('idx_tasks_due_date', table_name='tasks')
    op.drop_index('idx_tasks_carried', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('sprint_retros')
    op.drop_table('sprint_goals')
    op.drop_table('recurring_tasks')
    op.drop_table('templates')
    op.drop_table('tags')
    op.drop_table('sprints')
    op.drop_index('idx_inbox_resolved', table_name='inbox_items')
    op.drop_table('inbox_items')
    op.drop_index('idx_activity_entity', table_name='activity_log')
    op.drop_index('idx_activity_created', table_name='activity_log')
    op.drop_table('activity_log')
    # ### end Alembic commands ###
