"""daily plans

Revision ID: 95200a1815fb
Revises: 33deeb7dee6c
Create Date: 2026-08-06 12:49:41.139653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95200a1815fb'
down_revision: Union[str, None] = '33deeb7dee6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('focus', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_date')
    )
    op.create_table('daily_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.Text(), server_default='planned', nullable=False),
    sa.Column('pinned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source', sa.Text(), server_default='suggested', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('carried_from_plan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outcome IN ('planned', 'done', 'slipped', 'dropped')", name='ck_plan_items_outcome'),
    sa.CheckConstraint("source IN ('suggested', 'manual', 'claude')", name='ck_plan_items_source'),
    sa.ForeignKeyConstraint(['carried_from_plan_id'], ['daily_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['daily_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'task_id', name='uq_plan_items_plan_task')
    )
    op.create_index('idx_plan_items_outcome', 'daily_plan_items', ['outcome'], unique=False)
    op.create_index('idx_plan_items_plan', 'daily_plan_items', ['plan_id'], unique=False)
    op.create_index('idx_plan_items_task', 'daily_plan_items', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_plan_items_task', table_name='daily_plan_items')
    op.drop_index('idx_plan_items_plan', table_name='daily_plan_items')
    op.drop_index('idx_plan_items_outcome', table_name='daily_plan_items')
    op.drop_table('daily_plan_items')
    op.drop_table('daily_plans')
    # ### end Alembic commands ###
